[ fix ] stuck elaboration in parser library.
The type of the `Text.Parser` function `count` requires access to
the `min` function of `Data.Nat`. If `Data.Nat` has not been imported
in your parser module, then usages of `count` will fail to
elaborate correctly.

Thus, one can see errors of the form:

```
Error: While processing right hand side of header. Can't solve constraint
between: isSucc (min (between 1 6)) || Delay ?c2 and True.
```

This fix makes the import of `Data.Nat` public.