Auto-implicit `__con` now added before implicits.
The interface constraint variable `__con` was added after all implicit
variables before during interface elaboration, resulting in the variable
being unavailable in implicit arguments to interface methods.

For example, when type-checking

    interface A where
      x : Nat
      f : {pf : x = 0} -> ()

the type-checker would complain with

    Error: While processing type of f. Undefined name __con.

, whereas

    interface A where
      x : Nat
      f : (pf : x = 0) -> ()

would type-check just fine.

Note that the first example still doesn't type-check, but that's because
of another error.