Support "make -j" (#3135)
* Allow Idris2 to bootstrap with "make -j"

"linear" should explicitly depend on "base" so that "base" is built before
"linear", otherwise it can fail with:

> Error: Module Data.Nat not found
>
> Data.Linear.Copies:5:1--5:16
>  1 | module Data.Linear.Copies
>  2 |
>  3 | import Data.Linear.Bifunctor
>  4 | import Data.Linear.Notation
>  5 | import Data.Nat
>      ^^^^^^^^^^^^^^^

* Allow Idris2 to build with "make -j all"

"all: ${TARGET} libs" is bad because it means "${TARGET}" and "libs" can be
built independently. So "make -j" attempts to build them parallelly and
fail.